# Generated by Django 3.0.5 on 2020-11-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_by', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=30)),
                ('moved_from', models.CharField(max_length=50)),
                ('moved_to', models.CharField(max_length=50)),
                ('time_of_action', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_name', models.CharField(max_length=40)),
                ('task_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('task_description', models.CharField(max_length=1500)),
                ('created_by', models.CharField(max_length=40)),
                ('owner', models.CharField(max_length=40)),
                ('task_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_of_task', to='taskManager.TaskStatus')),
            ],
        ),
    ]
