# Generated by Django 3.0.5 on 2020-11-18 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=40)),
                ('task_id', models.IntegerField(unique=True)),
                ('task_description', models.CharField(max_length=1500)),
                ('created_by', models.CharField(max_length=40)),
                ('owner', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
